apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # We want to make sure that by default our application is not exposed
  type: ClusterIP 
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend